-- Tables
CREATE TABLE DEPARTMENT (
	ID_DEPARTMENT INT AUTO_INCREMENT NOT NULL,
    NAME_DEPARTMENT VARCHAR(50) NOT NULL,
    DESCRIPTION_DEPARTMENT VARCHAR(50) NOT NULL,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID_DEPARTMENT)
);

CREATE TABLE USER (
	ID_USER INT AUTO_INCREMENT NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    TYPE_USER VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(8) NOT NULL,
	ID_DEPARTMENT INT NOT NULL,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    CONSTRAINT PK_USER PRIMARY KEY (ID_USER),
    FOREIGN KEY FK_UXD_ID_DEPARTMENT (ID_DEPARTMENT) REFERENCES DEPARTMENT(ID_DEPARTMENT)
);

CREATE TABLE EMAIL (
	ID_EMAIL INT AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    CONSTRAINT PK_EMAIL PRIMARY KEY (ID_EMAIL)
);

CREATE TABLE USER_X_EMAIL (
	ID_USER INT NOT NULL,
	ID_EMAIL INT NOT NULL,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    FOREIGN KEY FK_UXE_ID_USER (ID_USER) REFERENCES USER(ID_USER),
    FOREIGN KEY FK_UXE_ID_EMAIL (ID_EMAIL) REFERENCES EMAIL(ID_EMAIL)
);

CREATE TABLE VEHICLE (
	VEHICLE_PLATE VARCHAR(6) NOT NULL,
    VEHICLE_BRAND VARCHAR(50) NOT NULL,
    VEHICLE_SERIES VARCHAR(50) NOT NULL,
    ID_USER INT NOT NULL,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    CONSTRAINT PK_VEHICLE PRIMARY KEY (VEHICLE_PLATE),
    FOREIGN KEY FK_VXU_ID_USER (ID_USER) REFERENCES USER(ID_USER)
);

CREATE TABLE PARKING (
	ID_PARKING VARCHAR(6) NOT NULL,
    NAME_PARKING VARCHAR (50) NOT NULL,
    DESCRIPTION_PARKING VARCHAR (150) NOT NULL,
    LOCATION_PARKING VARCHAR (150) NOT NULL,
    SCHEDULE_PARKING VARCHAR (50) NOT NULL,
    CREATEDAT DATE,
    UPDATEDAT DATE,
    CONSTRAINT PK_PARKING PRIMARY KEY (ID_PARKING)
);